name: publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: crates.io
    permissions: {}
    timeout-minutes: 20
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - run: cargo publish
